repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: mix-quality
        name: Mix Quality (format, credo, dialyzer)
        entry: mix quality
        language: system
        files: \.(ex|exs)$
        pass_filenames: false

      - id: mix-test
        name: Mix Test
        entry: mix test
        language: system
        files: \.(ex|exs)$
        pass_filenames: false
