repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: mix-format
        name: Mix Format
        entry: mix format --check-formatted
        language: system
        files: \.(ex|exs)$
        pass_filenames: false

      - id: mix-credo
        name: Mix Credo
        entry: mix credo --strict
        language: system
        files: \.(ex|exs)$
        pass_filenames: false

      - id: mix-test
        name: Mix Test
        entry: mix test
        language: system
        files: \.(ex|exs)$
        pass_filenames: false
