app = 'boonorbust3'
primary_region = 'sin'

[build]

[env]
  PHX_HOST = 'boonorbust3.fly.dev'


[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
